FROM centos:7

# Install necessary dependencies
RUN yum update -y && \
    yum install -y \
    python3 \
    python3-pip \
    python3-virtualenv \
    wget \
    tar \
    gzip \
    zip \
    make \
    gcc \
    && yum clean all

# Set up working directory
WORKDIR /workspace

# Copy build script and other necessary files
COPY scripts /workspace/scripts

# Run build script
ENTRYPOINT ["/workspace/scripts/build.sh"]